Repository algolia/algoliasearch-client-javascript, pull requests merged in 2020-04, with the labels that each got.

#1126 fix(apiKey): expose ApiKeyACL type
  packages/algoliasearch/src/builds/browser.ts
  packages/algoliasearch/src/builds/node.ts
  packages/client-search/src/methods/client/addApiKey.ts
  packages/client-search/src/types/ApiKeyType.ts
  packages/client-search/src/types/GetApiKeyResponse.ts
  packages/client-search/src/types/index.ts
Labels: TypeScript

#1138 chore(mcm): fixes user string length
  packages/client-common/src/__tests__/TestSuite.ts
Labels: chore

#1139 fix(types): Log types
  packages/client-common/src/__tests__/helpers.ts
  packages/client-search/src/__tests__/integration/get-logs.test.ts
  packages/client-search/src/types/Log.ts
Labels: DO NOT MERGE YET

#1147 feat(natural-languages): adds option
  packages/client-search/src/types/SearchOptions.ts
Labels: TypeScript
